version: "3"

services:
  vhserver:
    container_name: vhserver
    build: .
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
      - 27015:27015/tcp
      - 27015:27015/udp
      - 8080:8080 # make sure this matches your HEALTH_CHECK_PORT ENV
    volumes:
      - gsm-log-volume:/home/linuxgsm/gsm/log
      - steam-log-volume:/home/linuxgsm/.local/share/Steam/logs
      - valheim-server-volume:/home/linuxgsm/.config/unity3d/IronGate/Valheim
    # Customize these!
    environment:
      - SERVER_PASSWORD=test1234
      - SERVER_NAME=Test Server
      - SERVER_PUBLIC=0
      - SERVER_WORLD_NAME=TestWorld
      - HEALTH_CHECK_PORT=8080

volumes:
  gsm-log-volume:
  steam-log-volume:
  valheim-server-volume:
